import React, { useEffect, useMemo, useRef } from 'react';
import { Animated, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import * as Linking from 'expo-linking';
import { ArrowLeft, Instagram, TrendingUp, Wallet } from 'lucide-react-native';
import * as Haptics from 'expo-haptics';
import { useApp } from '@/contexts/AppContext';
import { Card } from '@/components/Card';
import { IconButton } from '@/components/IconButton';
import { palette, radius, space, type as typo } from '@/constants/theme';

function AnimatedValueText({ value, prefix = '' }: { value: number; prefix?: string }) {
  const animated = useRef(new Animated.Value(0)).current;
  const [display, setDisplay] = React.useState(0);

  useEffect(() => {
    const listenerId = animated.addListener(({ value: next }) => setDisplay(Math.round(next)));
    Animated.timing(animated, {
      toValue: value,
      duration: 900,
      useNativeDriver: false,
    }).start();
    return () => {
      animated.removeListener(listenerId);
    };
  }, [animated, value]);

  return <Text style={styles.valueNumber}>{prefix}{display.toLocaleString()}</Text>;
}

export default function ClosetValueScreen() {
  const router = useRouter();
  const { closetValueInsights } = useApp();
  const fade = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fade, { toValue: 1, duration: 400, useNativeDriver: true }).start();
  }, [fade]);

  const shareText = useMemo(() => {
    const brands = closetValueInsights.topBrands.join(', ') || 'My wardrobe staples';
    return `My closet is worth $${closetValueInsights.totalClosetValue.toLocaleString()}.\nTop brands: ${brands}.\nGenerated by MirrorMuse.`;
  }, [closetValueInsights.topBrands, closetValueInsights.totalClosetValue]);

  const onShareNative = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    await Share.share({ message: shareText });
  };

  const onShareInstagram = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const canOpen = await Linking.canOpenURL('instagram://');
    if (canOpen) {
      await Linking.openURL('instagram://camera');
      return;
    }
    await onShareNative();
  };

  const onShareTikTok = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const canOpen = await Linking.canOpenURL('snssdk1233://');
    if (canOpen) {
      await Linking.openURL('snssdk1233://');
      return;
    }
    await onShareNative();
  };

  return (
    <View style={styles.container}>
      <SafeAreaView style={styles.safeArea} edges={['top']}>
        <View style={styles.header}>
          <IconButton icon={<ArrowLeft size={18} color={palette.ink} />} onPress={() => router.back()} size={38} />
          <Text style={styles.title}>Closet Value</Text>
          <View style={{ width: 38 }} />
        </View>

        <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
          <Animated.View style={{ opacity: fade }}>
            <Card style={styles.heroCard}>
              <Text style={styles.heroLabel}>YOUR CLOSET VALUE</Text>
              <AnimatedValueText value={closetValueInsights.totalClosetValue} prefix="$" />
              <Text style={styles.heroSub}>Estimated resale value of your wardrobe</Text>
            </Card>
          </Animated.View>

          <Card style={styles.metricsCard} variant="flat">
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Items owned</Text>
              <Text style={styles.metricValue}>{closetValueInsights.itemCount}</Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Resale potential</Text>
              <Text style={styles.metricValue}>${closetValueInsights.resalePotential.toLocaleString()}</Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>High demand items</Text>
              <Text style={styles.metricValue}>{closetValueInsights.highDemandItems}</Text>
            </View>
          </Card>

          <Card>
            <Text style={styles.sectionTitle}>Top brands</Text>
            {closetValueInsights.topBrands.length > 0 ? closetValueInsights.topBrands.map((brand) => (
              <Text key={brand} style={styles.brandRow}>{brand}</Text>
            )) : <Text style={styles.emptyText}>Add branded items to reveal your top brands</Text>}
          </Card>

          <Card>
            <Text style={styles.sectionTitle}>Most valuable pieces</Text>
            {closetValueInsights.mostValuableItems.slice(0, 4).map((item) => (
              <View key={item.id} style={styles.metricRow}>
                <Text style={styles.metricLabel}>{item.color} {item.category}</Text>
                <Text style={styles.metricValue}>${(item.estimatedResaleValue || 0).toLocaleString()}</Text>
              </View>
            ))}
          </Card>

          <Card style={styles.shareCard}>
            <View style={styles.shareHeader}>
              <Wallet size={18} color={palette.secondary} />
              <Text style={styles.sectionTitle}>Share your closet value</Text>
            </View>
            <Text style={styles.shareBody}>“My closet is worth ${closetValueInsights.totalClosetValue.toLocaleString()}”</Text>
            <Text style={styles.shareMeta}>Generated by MirrorMuse</Text>
            <View style={styles.shareActions}>
              <TouchableOpacity style={styles.shareBtn} onPress={onShareInstagram}>
                <Instagram size={16} color={palette.ink} />
                <Text style={styles.shareBtnText}>Instagram</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.shareBtn} onPress={onShareTikTok}>
                <TrendingUp size={16} color={palette.ink} />
                <Text style={styles.shareBtnText}>TikTok</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.shareBtn} onPress={onShareNative}>
                <Text style={styles.shareBtnText}>Native Share</Text>
              </TouchableOpacity>
            </View>
          </Card>
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.warmWhite },
  safeArea: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: space.screen,
    paddingBottom: space.sm,
  },
  title: { ...typo.sectionHeader, color: palette.ink },
  content: { paddingHorizontal: space.screen, paddingBottom: 120, gap: space.md },
  heroCard: { alignItems: 'center' },
  heroLabel: { ...typo.caption, color: palette.inkMuted, letterSpacing: 0.7 },
  valueNumber: { ...typo.screenTitle, fontSize: 44, lineHeight: 50, color: palette.ink, marginVertical: 6 },
  heroSub: { ...typo.small, color: palette.inkMuted },
  metricsCard: {},
  metricRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 5 },
  metricLabel: { ...typo.body, color: palette.inkLight, textTransform: 'capitalize' },
  metricValue: { ...typo.bodyMedium, color: palette.ink },
  sectionTitle: { ...typo.bodyMedium, color: palette.ink, marginBottom: 8 },
  brandRow: { ...typo.body, color: palette.inkLight, marginBottom: 2 },
  emptyText: { ...typo.small, color: palette.inkMuted },
  shareCard: { backgroundColor: palette.secondaryLight },
  shareHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  shareBody: { ...typo.body, color: palette.ink, marginTop: 4 },
  shareMeta: { ...typo.small, color: palette.inkMuted, marginTop: 2, marginBottom: 10 },
  shareActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  shareBtn: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: palette.white,
  },
  shareBtnText: { ...typo.caption, color: palette.ink },
});
