import React, { useEffect, useRef } from 'react';
import { Animated, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import * as Linking from 'expo-linking';
import { ArrowLeft, Instagram, Sparkles, TrendingUp } from 'lucide-react-native';
import * as Haptics from 'expo-haptics';
import { useApp } from '@/contexts/AppContext';
import { Card } from '@/components/Card';
import { IconButton } from '@/components/IconButton';
import { palette, radius, space, type as typo } from '@/constants/theme';

function AnimatedBar({ label, value }: { label: string; value: number }) {
  const anim = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    Animated.timing(anim, {
      toValue: value,
      duration: 700,
      useNativeDriver: false,
    }).start();
  }, [anim, value]);

  const widthInterpolate = anim.interpolate({
    inputRange: [0, 100],
    outputRange: ['0%', '100%'],
  });

  return (
    <View style={{ marginBottom: 10 }}>
      <View style={styles.progressLabelRow}>
        <Text style={styles.progressLabel}>{label}</Text>
        <Text style={styles.progressValue}>{value}%</Text>
      </View>
      <View style={styles.progressTrack}>
        <Animated.View style={[styles.progressFill, { width: widthInterpolate }]} />
      </View>
    </View>
  );
}

export default function StylePersonalityScreen() {
  const router = useRouter();
  const { stylePersonalityInsights } = useApp();
  const fade = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fade, { toValue: 1, duration: 450, useNativeDriver: true }).start();
  }, [fade]);

  const shareText = `My fashion personality: ${stylePersonalityInsights.personality}.\nNeutral colors: ${stylePersonalityInsights.stats.neutralColorsPct}% · Streetwear influence: ${stylePersonalityInsights.stats.streetwearInfluencePct}% · Classic pieces: ${stylePersonalityInsights.stats.classicPiecesPct}%.\nGenerated by MirrorMuse.`;

  const shareNative = async () => {
    await Share.share({ message: shareText });
  };

  const shareInstagram = async () => {
    const canOpen = await Linking.canOpenURL('instagram://');
    if (canOpen) {
      await Linking.openURL('instagram://camera');
      return;
    }
    await shareNative();
  };

  const shareTikTok = async () => {
    const canOpen = await Linking.canOpenURL('snssdk1233://');
    if (canOpen) {
      await Linking.openURL('snssdk1233://');
      return;
    }
    await shareNative();
  };

  return (
    <View style={styles.container}>
      <SafeAreaView style={styles.safeArea} edges={['top']}>
        <View style={styles.header}>
          <IconButton icon={<ArrowLeft size={18} color={palette.ink} />} onPress={() => router.back()} size={38} />
          <Text style={styles.title}>Style Personality</Text>
          <View style={{ width: 38 }} />
        </View>

        <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
          <Animated.View style={{ opacity: fade }}>
            <Card style={styles.heroCard}>
              <Text style={styles.heroLabel}>Your Style Identity</Text>
              <Text style={styles.persona}>{stylePersonalityInsights.personality}</Text>
              <Text style={styles.description}>{stylePersonalityInsights.description}</Text>
            </Card>
          </Animated.View>

          <Card>
            <Text style={styles.sectionTitle}>Style stats</Text>
            <AnimatedBar label="Neutral colors" value={stylePersonalityInsights.stats.neutralColorsPct} />
            <AnimatedBar label="Streetwear influence" value={stylePersonalityInsights.stats.streetwearInfluencePct} />
            <AnimatedBar label="Classic pieces" value={stylePersonalityInsights.stats.classicPiecesPct} />
          </Card>

          <Card variant="flat">
            <Text style={styles.sectionTitle}>Wardrobe mix</Text>
            <Text style={styles.mixText}>Jackets: {stylePersonalityInsights.categoryDistribution.jackets}</Text>
            <Text style={styles.mixText}>Hoodies: {stylePersonalityInsights.categoryDistribution.hoodies}</Text>
            <Text style={styles.mixText}>Shirts: {stylePersonalityInsights.categoryDistribution.shirts}</Text>
            <Text style={styles.mixText}>Pants: {stylePersonalityInsights.categoryDistribution.pants}</Text>
            <Text style={styles.mixText}>Sneakers: {stylePersonalityInsights.categoryDistribution.sneakers}</Text>
          </Card>

          <Card style={styles.shareCard}>
            <View style={styles.shareHeader}>
              <Sparkles size={18} color={palette.accentDark} />
              <Text style={styles.sectionTitle}>Share your identity</Text>
            </View>
            <Text style={styles.shareBody}>“My fashion personality: {stylePersonalityInsights.personality}”</Text>
            <Text style={styles.shareMeta}>Generated by MirrorMuse</Text>
            <View style={styles.shareActions}>
              <TouchableOpacity style={styles.shareBtn} onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); shareInstagram(); }}>
                <Instagram size={16} color={palette.ink} />
                <Text style={styles.shareBtnText}>Instagram</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.shareBtn} onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); shareTikTok(); }}>
                <TrendingUp size={16} color={palette.ink} />
                <Text style={styles.shareBtnText}>TikTok</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.shareBtn} onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); shareNative(); }}>
                <Text style={styles.shareBtnText}>Native Share</Text>
              </TouchableOpacity>
            </View>
          </Card>
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.warmWhite },
  safeArea: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: space.screen,
    paddingBottom: space.sm,
  },
  title: { ...typo.sectionHeader, color: palette.ink },
  content: { paddingHorizontal: space.screen, paddingBottom: 120, gap: space.md },
  heroCard: { alignItems: 'center' },
  heroLabel: { ...typo.caption, color: palette.inkMuted },
  persona: { ...typo.screenTitle, fontSize: 36, lineHeight: 42, color: palette.ink, textAlign: 'center', marginTop: 4 },
  description: { ...typo.body, color: palette.inkMuted, textAlign: 'center', marginTop: 6 },
  sectionTitle: { ...typo.bodyMedium, color: palette.ink, marginBottom: 8 },
  progressLabelRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  progressLabel: { ...typo.small, color: palette.inkMuted },
  progressValue: { ...typo.small, color: palette.ink },
  progressTrack: {
    height: 9,
    borderRadius: radius.pill,
    backgroundColor: palette.borderLight,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: radius.pill,
    backgroundColor: palette.accent,
  },
  mixText: { ...typo.body, color: palette.inkLight, marginBottom: 2 },
  shareCard: { backgroundColor: palette.accentLight },
  shareHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  shareBody: { ...typo.body, color: palette.ink, marginTop: 4 },
  shareMeta: { ...typo.small, color: palette.inkMuted, marginTop: 2, marginBottom: 10 },
  shareActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  shareBtn: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: palette.white,
  },
  shareBtnText: { ...typo.caption, color: palette.ink },
});
